### PR TITLE
Don 128 wishcard tests + DON-130

### PR DESCRIPTION
**Pull request by Jacobjeevan**
- Added test cases for donor users (email verified and email unverified)
- Fixed message permissions bug (Messaging was restricted to agency users on backend -> now it's open to all verified Donor users)
- DON-130 Route bug
- Changed GET route to display all wishcards, rather than one with published status (will have to update once we add edit/publish functionality)

### CODE REVIEW

**Review by Enubia — APPROVED** [review]

**Comment by Enubia** [comment]
@Jacobjeevan please update with master

**Comment by Jacobjeevan** [comment]
> @Jacobjeevan please update with master

Done :+1:

**Comment by gnorbsl** [comment]
wont this also display drafts?

**Comment by gnorbsl** [comment]
I assumed we already have publish functionality for admins, since we manually publish them now to prevent another giftcard disaster

**Comment by Jacobjeevan** [comment]
> wont this also display drafts?

It will, yes.

> I assumed we already have publish functionality for admins, since we manually publish them now to prevent another giftcard disaster

Is that available on frontend though? I don't think it is; I changed it back since merging into prod would cause all existing wishcards to just disappear (alternatively, could use mongo-cli to set all existing wishcards to published status).

**Comment by Enubia** [comment]
@Jacobjeevan is this branch ready for merge now or do you need to do some additional changes?

**Comment by Jacobjeevan** [comment]
> @Jacobjeevan is this branch ready for merge now or do you need to do some additional changes?

This will work for current version. Backend limits wishcard creation to verified agencies (and since we don't have logic to approve wishcards, apart from through mongo cli), this will work (current wishcards have no status associated with them).

**Pull request merged**
