### PR TITLE
fix frontend bug for /profile page edit features

### PR DESCRIPTION
**Pull request by nguyenit67**
I've fix the frontend bug for /profile page edit features, but when I reload the page, the user account infomation (fName, lName, aboutMe) didn't update although the data has been sent in the request payload when I opened DevTools (I also check if the info has been updated in Mongo Compass, yes it was), and only when I sign out and log in again the information becomes up-to-date

### CODE REVIEW

**Comment by nguyenit67** [comment]
I suspect the frontend code use the old user data in the browser storage (cookie, localStorage) and the problem lies in this line https://github.com/donategifts/donategifts/blob/master/src/index.ts#L108

**Review by Enubia — APPROVED** [review]
LGTM!

**Comment by Enubia** [comment]
> I suspect the frontend code use the old user data in the browser storage (cookie, localStorage) and the problem lies in this line https://github.com/donategifts/donategifts/blob/master/src/index.ts#L108

Yes this is correct, the session data isn't updated correctly. Please raise an issue to fix this behavior.

**Comment by nguyenit67** [comment]
I've raised the issue at #584, please check it out

**Comment by stacysealky** [comment]
resolves #575

**Pull request merged**
